using System;
using System.Collections.Generic;
using System.Text;

namespace Sekai.MusicScoreMaker.Ingame.Utilities
{
	internal static class HersheyStrokeFont
	{
		private const string EncodedData = "ICA2OTkgIDFKWgogIDcxNCAgOU1XUkZSVCBSUllRWlJbU1pSWQogIDcxNyAgNkpaTkZOTSBSVkZWTQogIDczMyAxMkhdU0JMYiBSWUJSYiBSTE9aTyBSS1VZVQogIDcxOSAyN0hcUEJQXyBSVEJUXyBSWUlXR1RGUEZNR0tJS0tMTU1OT09VUVdSWFNZVVlYV1pUW1BbTVpLWAogMjI3MSAzMkZeW0ZJWyBSTkZQSFBKT0xNTUtNSUtJSUpHTEZORlBHU0hWSFlHW0YgUldUVVVUV1RZVltYW1paW1hbVllUV1QKICA3MzQgMzVFX1xPXE5bTVpNWU5YUFZVVFhSWlBbTFtKWklZSFdIVUlTSlJRTlJNU0tTSVJHUEZOR01JTUtOTlBRVVhXWllbW1tcWlxZCiAgNzMxICA4TVdSSFFHUkZTR1NJUktRTAogIDcyMSAxMUtZVkJURFJHUEtPUE9UUFlSXVRgVmIKICA3MjIgMTFLWU5CUERSR1RLVVBVVFRZUl1QYE5iCiAyMjE5ICA5SlpSRlJSIFJNSVdPIFJXSU1PCiAgNzI1ICA2RV9SSVJbIFJJUltSCiAgNzExICA5TVdTWlJbUVpSWVNaU1xSXlFfCiAgNzI0ICAzRV9JUltSCiAgNzEwICA2TVdSWVFaUltTWlJZCiAgNzIwICAzR11bQkliCiAgNzAwIDE4SFxRRk5HTEpLT0tSTFdOWlFbU1tWWlhXWVJZT1hKVkdTRlFGCiAgNzAxICA1SFxOSlBJU0ZTWwogIDcwMiAxNUhcTEtMSk1ITkdQRlRGVkdXSFhKWExXTlVRS1tZWwogIDcwMyAxNkhcTUZYRlJOVU5XT1hQWVNZVVhYVlpTW1BbTVpMWUtXCiAgNzA0ICA3SFxVRktUWlQgUlVGVVsKICA3MDUgMThIXFdGTUZMT01OUE1TTVZOWFBZU1lVWFhWWlNbUFtNWkxZS1cKICA3MDYgMjRIXFhJV0dURlJGT0dNSkxPTFRNWE9aUltTW1ZaWFhZVVlUWFFWT1NOUk5PT01RTFQKICA3MDcgIDZIXFlGT1sgUktGWUYKICA3MDggMzBIXFBGTUdMSUxLTU1PTlNPVlBYUllUWVdYWVdaVFtQW01aTFlLV0tUTFJOUFFPVU5XTVhLWElXR1RGUEYKICA3MDkgMjRIXFhNV1BVUlJTUVNOUkxQS01LTExJTkdRRlJGVUdXSVhNWFJXV1VaUltQW01aTFgKICA3MTIgMTJNV1JNUU5ST1NOUk0gUlJZUVpSW1NaUlkKICA3MTMgMTVNV1JNUU5ST1NOUk0gUlNaUltRWlJZU1pTXFJeUV8KIDIyNDEgIDRGXlpJSlJaWwogIDcyNiAgNkVfSU9bTyBSSVVbVQogMjI0MiAgNEZeSklaUkpbCiAgNzE1IDIxSVtMS0xKTUhOR1BGVEZWR1dIWEpYTFdOVk9SUVJUIFJSWVFaUltTWlJZCiAyMjczIDU2RWBXTlZMVEtRS09MTk1NUE1TTlVQVlNWVVVWUyBSUUtPTU5QTlNPVVBWIFJXS1ZTVlVYVlpWXFRdUV1PXExbSllIV0dURlFGTkdMSEpKSUxIT0hSSVVKV0xZTlpRW1RbV1pZWVpYIFJYS1dTV1VYVgogIDUwMSAgOUlbUkZKWyBSUkZaWyBSTVRXVAogIDUwMiAyNEdcS0ZLWyBSS0ZURldHWEhZSllMWE5XT1RQIFJLUFRQV1FYUllUWVdYWVdaVFtLWwogIDUwMyAxOUhdWktZSVdHVUZRRk9HTUlMS0tOS1NMVk1YT1pRW1VbV1pZWFpWCiAgNTA0IDE2R1xLRktbIFJLRlJGVUdXSVhLWU5ZU1hWV1hVWlJbS1sKICA1MDUgMTJIW0xGTFsgUkxGWUYgUkxQVFAgUkxbWVsKICA1MDYgIDlIWkxGTFsgUkxGWUYgUkxQVFAKICA1MDcgMjNIXVpLWUlXR1VGUUZPR01JTEtLTktTTFZNWE9aUVtVW1daWVhaVlpTIFJVU1pTCiAgNTA4ICA5R11LRktbIFJZRllbIFJLUFlQCiAgNTA5ICAzTlZSRlJbCiAgNTEwIDExSlpWRlZWVVlUWlJbUFtOWk1ZTFZMVAogIDUxMSAgOUdcS0ZLWyBSWUZLVCBSUE9ZWwogIDUxMiAgNkhZTEZMWyBSTFtYWwogIDUxMyAxMkZeSkZKWyBSSkZSWyBSWkZSWyBSWkZaWwogIDUxNCAgOUddS0ZLWyBSS0ZZWyBSWUZZWwogIDUxNSAyMkddUEZOR0xJS0tKTkpTS1ZMWE5aUFtUW1ZaWFhZVlpTWk5ZS1hJVkdURlBGCiAgNTE2IDE0R1xLRktbIFJLRlRGV0dYSFlKWU1YT1dQVFFLUQogIDUxNyAyNUddUEZOR0xJS0tKTkpTS1ZMWE5aUFtUW1ZaWFhZVlpTWk5ZS1hJVkdURlBGIFJTV1ldCiAgNTE4IDE3R1xLRktbIFJLRlRGV0dYSFlKWUxYTldPVFBLUCBSUlBZWwogIDUxOSAyMUhcWUlXR1RGUEZNR0tJS0tMTU1OT09VUVdSWFNZVVlYV1pUW1BbTVpLWAogIDUyMCAgNkpaUkZSWyBSS0ZZRgogIDUyMSAxMUddS0ZLVUxYTlpRW1NbVlpYWFlVWUYKICA1MjIgIDZJW0pGUlsgUlpGUlsKICA1MjMgMTJGXkhGTVsgUlJGTVsgUlJGV1sgUlxGV1sKICA1MjQgIDZIXEtGWVsgUllGS1sKICA1MjUgIDdJW0pGUlBSWyBSWkZSUAogIDUyNiAgOUhcWUZLWyBSS0ZZRiBSS1tZWwogMjIyMyAxMktZT0JPYiBSUEJQYiBST0JWQiBST2JWYgogIDgwNCAgM0tZS0ZZXgogMjIyNCAxMktZVEJUYiBSVUJVYiBSTkJVQiBSTmJVYgogMjI2MiAxMUpaUExSSVRMIFJNT1JKV08gUlJKUlsKICA5OTkgIDNKWkpdWl0KICA3MzAgIDhNV1NGUkdRSVFLUkxTS1JKCiAgNjAxIDE4SVxYTVhbIFJYUFZOVE1RTU9OTVBMU0xVTVhPWlFbVFtWWlhYCiAgNjAyIDE4SFtMRkxbIFJMUE5OUE1TTVVOV1BYU1hVV1hVWlNbUFtOWkxYCiAgNjAzIDE1SVtYUFZOVE1RTU9OTVBMU0xVTVhPWlFbVFtWWlhYCiAgNjA0IDE4SVxYRlhbIFJYUFZOVE1RTU9OTVBMU0xVTVhPWlFbVFtWWlhYCiAgNjA1IDE4SVtMU1hTWFFXT1ZOVE1RTU9OTVBMU0xVTVhPWlFbVFtWWlhYCiAgNjA2ICA5TVlXRlVGU0dSSlJbIFJPTVZNCiAgNjA3IDIzSVxYTVhdV2BWYVRiUWJPYSBSWFBWTlRNUU1PTk1QTFNMVU1YT1pRW1RbVlpYWAogIDYwOCAxMUlcTUZNWyBSTVFQTlJNVU1XTlhRWFsKICA2MDkgIDlOVlFGUkdTRlJFUUYgUlJNUlsKICA2MTAgMTJNV1JGU0dURlNFUkYgUlNNU15SYVBiTmIKICA2MTEgIDlJWk1GTVsgUldNTVcgUlFTWFsKICA2MTIgIDNOVlJGUlsKICA2MTMgMTlDYUdNR1sgUkdRSk5MTU9NUU5SUVJbIFJSUVVOV01aTVxOXVFdWwogIDYxNCAxMUlcTU1NWyBSTVFQTlJNVU1XTlhRWFsKICA2MTUgMThJXFFNT05NUExTTFVNWE9aUVtUW1ZaWFhZVVlTWFBWTlRNUU0KICA2MTYgMThIW0xNTGIgUkxQTk5QTVNNVU5XUFhTWFVXWFVaU1tQW05aTFgKICA2MTcgMThJXFhNWGIgUlhQVk5UTVFNT05NUExTTFVNWE9aUVtUW1ZaWFgKICA2MTggIDlLWE9NT1sgUk9TUFBSTlRNV00KICA2MTkgMThKW1hQV05UTVFNTk5NUE5SUFNVVFdVWFdYWFdaVFtRW05aTVgKICA2MjAgIDlNWVJGUldTWlVbV1sgUk9NVk0KICA2MjEgMTFJXE1NTVdOWlBbU1tVWlhXIFJYTVhbCiAgNjIyICA2SlpMTVJbIFJYTVJbCiAgNjIzIDEyR11KTU5bIFJSTU5bIFJSTVZbIFJaTVZbCiAgNjI0ICA2SltNTVhbIFJYTU1bCiAgNjI1IDEwSlpMTVJbIFJYTVJbUF9OYUxiS2IKICA2MjYgIDlKW1hNTVsgUk1NWE0gUk1bWFsKIDIyMjUgNDBLWVRCUkNRRFBGUEhRSlJLU01TT1FRIFJSQ1FFUUdSSVNKVExUTlNQT1JTVFRWVFhTWlJbUV1RX1JhIFJRU1NVU1dSWVFaUFxQXlFgUmFUYgogIDcyMyAgM05WUkJSYgogMjIyNiA0MEtZUEJSQ1NEVEZUSFNKUktRTVFPU1EgUlJDU0VTR1JJUUpQTFBOUVBVUlFUUFZQWFFaUltTXVNfUmEgUlNTUVVRV1JZU1pUXFReU2BSYVBiCiAyMjQ2IDI0Rl5JVUlTSlBMT05PUFBUU1ZUWFRaU1tRIFJJU0pRTFBOUFBRVFRWVVhVWlRbUVtPCiAgNzE4IDE0S1lRRk9HTklOS09NUU5TTlVNVktWSVVHU0ZRRgo=";
		private static readonly Dictionary<char, int> CharacterNumbers = new Dictionary<char, int>
		{
			['A']=501,['B']=502,['C']=503,['D']=504,['E']=505,['F']=506,['G']=507,['H']=508,['I']=509,['J']=510,['K']=511,['L']=512,['M']=513,['N']=514,['O']=515,['P']=516,['Q']=517,['R']=518,['S']=519,['T']=520,['U']=521,['V']=522,['W']=523,['X']=524,['Y']=525,['Z']=526,
			['a']=601,['b']=602,['c']=603,['d']=604,['e']=605,['f']=606,['g']=607,['h']=608,['i']=609,['j']=610,['k']=611,['l']=612,['m']=613,['n']=614,['o']=615,['p']=616,['q']=617,['r']=618,['s']=619,['t']=620,['u']=621,['v']=622,['w']=623,['x']=624,['y']=625,['z']=626,
			[' ']=699,['0']=700,['1']=701,['2']=702,['3']=703,['4']=704,['5']=705,['6']=706,['7']=707,['8']=708,['9']=709,['.']=710,[',']=711,[':']=712,[';']=713,['!']=714,['?']=715,['\"']=717,['$']=719,['/']=720,['(']=721,[')']=722,['|']=723,['-']=724,['+']=725,['=']=726,['\'']=731,['#']=733,['&']=734,['\\']=804,['_']=999,['*']=2219,['[']=2223,[']']=2224,['{']=2225,['}']=2226,['<']=2241,['>']=2242,['~']=2246,['%']=2271,['@']=2273
		};
		private static Dictionary<int, Glyph> _glyphs;

		internal sealed class Glyph
		{
			public float Width;
			public readonly List<List<ArtStrokePoint>> Paths = new List<List<ArtStrokePoint>>();
		}

		public static Glyph Get(char character)
		{
			if (character == '^') return MakeGlyph(16, new ArtStrokePoint(2, 14), new ArtStrokePoint(8, 5), new ArtStrokePoint(14, 14));
			if (character == '`') return MakeGlyph(10, new ArtStrokePoint(3, 5), new ArtStrokePoint(7, 9));
			if (!CharacterNumbers.TryGetValue(character, out int number)) throw new NotSupportedException($"Hershey does not contain '{character}'.");
			EnsureLoaded();
			if (!_glyphs.TryGetValue(number, out Glyph glyph)) throw new InvalidOperationException($"Missing Hershey glyph {number}.");
			return glyph;
		}

		private static Glyph MakeGlyph(float width, params ArtStrokePoint[] points)
		{
			Glyph glyph = new Glyph { Width = width };
			glyph.Paths.Add(new List<ArtStrokePoint>(points));
			return glyph;
		}

		private static void EnsureLoaded()
		{
			if (_glyphs != null) return;
			_glyphs = new Dictionary<int, Glyph>();
			string data = Encoding.ASCII.GetString(Convert.FromBase64String(EncodedData));
			foreach (string rawLine in data.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
			{
				if (rawLine.Length < 10 || !int.TryParse(rawLine.Substring(0, 5), out int number)) continue;
				int left = rawLine[8] - 'R';
				int right = rawLine[9] - 'R';
				Glyph glyph = new Glyph { Width = right - left };
				List<ArtStrokePoint> path = new List<ArtStrokePoint>();
				for (int i = 10; i + 1 < rawLine.Length; i += 2)
				{
					int x = rawLine[i] - 'R';
					int y = rawLine[i + 1] - 'R';
					if (x == -50 && y == 0)
					{
						if (path.Count >= 2) glyph.Paths.Add(path);
						path = new List<ArtStrokePoint>();
					}
					else path.Add(new ArtStrokePoint(x - left, -y + 11));
				}
				if (path.Count >= 2) glyph.Paths.Add(path);
				_glyphs[number] = glyph;
			}
		}
	}
}
